//! This module contains helper functions that code generated by the derive
//! macros uses.
//!
//! These items need to be part of the public interface of the library, or else
//! they wouldn't be accessible from the traits derived in users of this
//! library.
//!
//! Despite the items being public, you should **NOT** use these items in your
//! code. This module exists strictly to support the derive macros where
//! standalone code generation is not possible due to Rust's generic programming
//! limitations.

use crate::{bit::Error as BitError, deserialize::Deserializer, serialize::SerializerOutput};

pub fn bit_error_to_error_se<S: SerializerOutput>(_: &S, bit_error: BitError) -> S::Error {
    bit_error.into()
}

pub fn bit_error_to_error_de<D: Deserializer>(_: &D, bit_error: BitError) -> D::Error {
    bit_error.into()
}
